### ISSUE TITLE
TypeError: Cannot read property '__container__' of undefined

### ISSUE THREAD

**Issue by matthewsecrist** [matthewsecrist/Saga-Frontend#1]
When running the site in production, the login/register routes do not render, and all console throws is the vendor bundle with a line of minimized JS.

**Comment by matthewsecrist** [comment]
Issue has been fixed, seems to have been caused by ember-bulma.

**Comment by crodriguez1a** [comment]
@matthewsecrist What release did you experience this issue with and what release fixed it?

**Comment by matthewsecrist** [comment]
@crodriguez1a It was on 0.2.0 and 0.3.0. The release of 0.3.0 did not fix it, what ended up fixing it was replacing {{#bulma-container}} elements with <div class="container">. This was only happening on production and seems to be in relation to ebryn/ember-model#457

**Comment by crodriguez1a** [comment]
@matthewsecrist Thanks man. 

cc/ @alexdiliberto
